### ISSUE TITLE
Doesn't appear in HAcs despite saying so in installation

### ISSUE THREAD

**Issue by hacslarshome** [bruxy70/Garbage-Collection#12] opened 2019-09-10 07:00 UTC
https://github.com/custom-components/hacs

Doesn't include this repo. I think it used to, but doesn't anymore.
I put at issue in HACs, but was told it wasn't a problem on their end.

**Comment by bruxy70** [comment] 2019-09-10 07:05
Thanks. I will push new release.

**Comment by Vatoe** [comment] 2019-09-10 09:18
I think something broke in version 1.10. All created sensors come up with a null next date. Downgrading fixes the problem.

**Comment by bruxy70** [comment] 2019-09-10 09:39
@Vatoe that was another issue that I overlooked. Sorry for that. This is fixed now in 1.11.
This does not solve the disappearance from HACS. For that I fixed the repo, made PR, the merge is still pending. No idea when this will happen.

**Comment by bruxy70** [comment] 2019-09-10 10:55
Looks like it is back. Can you see it? Thanks for discovering that.

**Comment by Vatoe** [comment] 2019-09-10 11:17
No problem at all. This component which I only discovered has been great. Yes I have updated to 1.11 and it works as intended. I can see it through HAC's on my end?

**Comment by hacslarshome** [comment] 2019-09-10 11:29
Yes. The Garbage-Collection shows up as it should now.
Thank you for the quick fix.

**Closed** 2019-09-10 11:43 UTC
