### ISSUE TITLE
Days are out for General Waste

### ISSUE THREAD

**Issue by grantclem** [bruxy70/Garbage-Collection#230] opened 2020-12-28 22:43 UTC
**Describe the bug**

All of a sudden the days are out of sync for the general waste sensor which is a weekly event- the others alternate odds and even weeks.

![image](https://user-images.githubusercontent.com/30598978/103246962-2cca9100-49a0-11eb-943e-5fd6c6c99150.png)

![image](https://user-images.githubusercontent.com/30598978/103246984-410e8e00-49a0-11eb-93b0-0ca5d4dc7913.png)

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? :  

Config Flow

```yaml

```

**Error log/debug information**

```txt

```

**Screenshots**

**Version**

Integration version: Latest

Home Assistant version: Latest

**Comment by bruxy70** [comment] 2020-12-29 11:41
I can't reproduce it, my weekly sensors run fine. Can you please send debug logs? Also, what is wrong? For what day is the sensor configured? Did you configure to skip any holidays?

**Comment by grantclem** [comment] 2020-12-29 11:52
Hi, thanks for your response - I have since delete and re-added the sensor and appears to be ok now. Weekday is Wednesday and was set from Jan to December from memory, so not sure if that was the issue. Does it time out after 12 months? Does this have to be an option? It never was an issue with public holidays in the past. Thanks again for your work

**Comment by bruxy70** [comment] 2020-12-29 11:54
Nop, it does not expire. Since we can't replicate it, I will close the issue for now.

**Closed by bruxy70** 2020-12-29 11:54 UTC
Labels: bug
