### ISSUE TITLE
Request for option to remove date from verbose mode

### ISSUE THREAD

**Issue by Kranzy** [bruxy70/Garbage-Collection#28] opened 2019-10-25 00:27 UTC
Hi, just wondering if there is a current way to achieve this or if its not too difficult to impliment. I like using verbose mode as it handles the number of days, tomorrow, today logic, but it would be great to have the option to turn the date on or off when you're displaying it in the HA front end.

**Comment by bruxy70** [comment] 2019-10-25 06:45
Duplicate of the issue #23

**Closed by bruxy70** 2019-10-25 06:45 UTC
